apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-api
      version: v1
  template:
    metadata:
      labels:
        app: another-api
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: another-api
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: another-api
  labels:
    app: another-api
spec: 
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: another-api